language: go
sudo: false

matrix:
  include:
    - go: 1.11.x
    - go: 1.12.x
    - go: 1.13.x
    - go: master
  allow_failures:
    - go: master

install:
  - go install ./vendor/golang.org/x/tools/cmd/goimports
  - go install ./vendor/golang.org/x/lint/golint

go_import_path: github.com/cloudflare/gokeyless

script:
  - make vet lint test-nohsm test-trust
