language: go
go:
  - tip
before_script:
  - go get golang.org/x/tools/cmd/vet
  - go get golang.org/x/tools/cmd/goimports
  - go get -u github.com/golang/lint/golint
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/modocache/gover
  - go get github.com/mattn/goveralls
  - go get -v github.com/GeertJohan/fgt
script:
  - go get github.com/cloudflare/gokeyless/...
  - go test github.com/cloudflare/gokeyless/...
  - go vet github.com/cloudflare/gokeyless/...
  - fgt golint github.com/cloudflare/gokeyless/...
notifications:
  email:
    recipients:
    - jacob@cloudflare.com
    on_success: never
    on_failure: change
