# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true

required = [
  "golang.org/x/lint/golint",
  "golang.org/x/tools/cmd/goimports",
]

[[constraint]]
  name = "github.com/cloudflare/cfssl"
  branch = "master"

[[constraint]]
  name = "golang.org/x/crypto"
  branch = "master"

[[constraint]]
  branch = "master"
  name = "github.com/cloudflare/backoff"

[[constraint]]
  branch = "master"
  name = "github.com/cloudflare/go-metrics"

[[constraint]]
  branch = "master"
  name = "github.com/joshlf/testutil"

[[constraint]]
  branch = "master"
  name = "github.com/lziest/ttlcache"

[[constraint]]
  name = "github.com/miekg/dns"
  version = "1.0.4"

[[constraint]]
  branch = "master"
  name = "github.com/prometheus/client_golang"

[[constraint]]
  name = "github.com/ThalesIgnite/crypto11"
  version = "v1.0.0"

# crypto11 uses go modules so dep doesn't understand its dependencies
[[override]]
  name = "github.com/miekg/pkcs11"
  revision = "a667d056470f6e0da7facaff2466f0d2645e35d7"

# https://github.com/ThalesIgnite/crypto11/issues/35
[[override]]
  name = "github.com/vitessio/vitess"
  revision = "5d425edc0cafad159bddaaaa9dc4505c98e8acbf"

[[override]]
  branch = "master"
  name = "github.com/youtube/vitess"

[prune]
  go-tests = true
  unused-packages = true
